@csrf
@if(isset($equipment)) @method('PUT') @endif
<div class="space-y-5">
    <div><label for="profile_id" class="block font-medium">Profile</label><select id="profile_id" name="profile_id" required class="mt-2 w-full rounded-lg border border-gray-300 bg-white p-3 dark:border-gray-700 dark:bg-gray-800 dark:text-white"><option value="">Choose a profile</option>@foreach($profiles as $profile)<option value="{{ $profile->id }}" {{ (string) old('profile_id', $equipment->profile_id ?? request('profile_id')) === (string) $profile->id ? 'selected' : '' }}>{{ $profile->user->name }} · {{ $profile->neighborhood }}</option>@endforeach</select>@error('profile_id')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    @foreach ([['name','Name'],['type','Type']] as [$field,$label])<div><label for="{{ $field }}" class="block font-medium">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $equipment?->$field) }}" required class="mt-2 w-full rounded-lg border border-gray-300 p-3 dark:border-gray-700 dark:bg-gray-800 dark:text-white">@error($field)<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>@endforeach
    <div><label for="description" class="block font-medium">Description</label><textarea id="description" name="description" rows="4" class="mt-2 w-full rounded-lg border border-gray-300 p-3 dark:border-gray-700 dark:bg-gray-800 dark:text-white">{{ old('description', $equipment?->description) }}</textarea>@error('description')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
    <div><label for="priority_level" class="block font-medium">Priority</label><select id="priority_level" name="priority_level" required class="mt-2 w-full rounded-lg border border-gray-300 bg-white p-3 dark:border-gray-700 dark:bg-gray-800 dark:text-white"><option value="">Choose priority</option>@foreach(['low','medium','high'] as $level)<option value="{{ $level }}" {{ old('priority_level', $equipment?->priority_level) === $level ? 'selected' : '' }}>{{ ucfirst($level) }}</option>@endforeach</select>@error('priority_level')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
</div>
<div class="mt-7 flex gap-3"><button class="rounded-lg bg-orange-600 px-5 py-3 font-semibold text-white hover:bg-orange-700">Save equipment</button><a href="{{ route('admin.equipment.index') }}" class="rounded-lg border border-gray-300 px-5 py-3 dark:border-gray-700">Cancel</a></div>
