@csrf
@if($signalement) @method('PUT') @endif
<x-ha.field name="user_id" :label="__('Resident')"><select id="user_id" name="user_id" class="ha-select" required><option value="">{{ __('Choose a resident') }}</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) old('user_id', $signalement?->user_id) === (string) $user->id)>{{ $user->name }} — {{ $user->email }}</option>@endforeach</select></x-ha.field>
<x-ha.field name="coupure_id" :label="__('Associated outage')"><select id="coupure_id" name="coupure_id" class="ha-select" ><option value="">{{ __('None') }}</option>@foreach($coupures as $coupureOption)<option value="{{ $coupureOption->id }}" @selected((string) old('coupure_id', $signalement?->coupure_id) === (string) $coupureOption->id)>#{{ $coupureOption->id }} — {{ $coupureOption->quartier->nom }} — {{ $coupureOption->date_debut->format('d/m/Y H:i') }} ({{ $coupureOption->statut }})</option>@endforeach</select></x-ha.field>
<x-ha.input name="adresse" :label="__('Address')" :value="old('adresse', $signalement?->adresse)" required maxlength="255" />
<x-ha.field name="description" :label="__('Description')"><textarea id="description" name="description" class="ha-textarea" required maxlength="10000" rows="5">{{ old('description', $signalement?->description) }}</textarea></x-ha.field>
<x-ha.field name="statut" :label="__('Status')"><select id="statut" name="statut" class="ha-select" required>@foreach(\App\Models\Signalement::STATUTS as $value)<option value="{{ $value }}" @selected(old('statut', $signalement?->statut) === $value)>{{ $value }}</option>@endforeach</select></x-ha.field>
<div class="ha-form-actions"><a class="ha-btn ha-btn--outline" href="{{ route('admin.signalements.index') }}">{{ __('Cancel') }}</a><button class="ha-btn ha-btn--primary">{{ __('Save report') }}</button></div>

